# *** Radiation Mapping Parameters ***

# This parameter file is loaded in the radiation mapping launch files



# *** General***

# The number of threads used for the ROS spinner
rosSpinnerThreads: 4

# Set to true to enable the online evaluation of the 3D model
enableOnline3DEvaluation: true

# Set to true to enable spatial filtering of samples
enableSpatialSampleFiltering: false

# *** ROS topics ***

# The topic on which the radiation measurements are published
subscribeTopic: "/dose_rate"

# The topic on which the accumulated pointcloud of the environment is published
environmentCloudTopic: "/pointcloud_accumulated"

# The topic on which the grid map of the environment is published
environmentMapTopic: "/map"

# The key of the CPS value in the radiation message
messageKey_cps: "cps"

# The key of the rate value in the radiation message
messageKey_rate: "rate"

# The key of the frame id in the radiation message
messageKey_frameId: "frame_id"

# The unit of the radiation values used for display
radiationUnit: "µSv/h"



# *** Source prediciton***

# Potential sources need to be at least meanFactor times stronger than the mean value of all measurements
meanFactor: 1

# Potential sources need to have a dose rate of at least minSourceStrength
minSourceStrength: 50.0 #in model unit



# *** 2D model ***

# The radius of the circle used for sampling the 2D model
circleRadius: 5.0 # meter

# The minimum distance that a sample needs to the last sample to be included in the model
minDistanceBetweenSamples2d: 0.2 # meter

# The minimum time between two updates of the 2D model
minUpdateTime2d: 100 # milliseconds



# *** GridMap ***

# The resolution of the grid map generated by the system
gridMapResolution: 0.1 # meter



# *** 3D model ***

# The radius of the circle used for sampling the 3D model
gpLocalRadius: 5.0 # meter

# The minimum distance that a sample needs to the last sample to be included in the model
minDistanceBetweenSamples3d: 0.1 # meter

# The minimum time between two updates of the 3D model
minUpdateTime3d: 500 # milliseconds



# *** 3D point cloud ***

# The visualization point cloud is downsampled in three distance levels, to improve visibility
# These distances are given below
distanceCutoffLevels: [1.0, 3.0, 5] # meter

# The number of points that are kept in each distance level
pointCloud3DSizeLevels: [15000, 10000, 10000]